# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Podcast Theme"
license = "MIT"
licenselink = "https://github.com/ooprod/podcast-theme/blob/master/LICENSE"
description = "A Hugo theme for static-generated podcast sites"
#homepage = "http://example.com/"
tags = ["podcast", "bulma", "sass"]
features = ["itunes rss", "bulma","sass", "google analitics"]
min_version = "0.41"

[author]
  name = "Ivan Belyavtsev"
  homepage = "https://djbelyak.ru"
